source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

target 'DMRProxyServer_Example' do
#  pod 'Alamofire'
  pod 'DMRProxyServer', :path => '../'


  target 'DMRProxyServer_Tests' do
    inherit! :search_paths
    inhibit_all_warnings!

    
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
